@TodoApi_HostAddress = http://localhost:5024
@id = d3449880-fd00-433b-b463-8eafe72b6704


GET {{TodoApi_HostAddress}}/todos/
Accept: application/json

###

POST {{TodoApi_HostAddress}}/todos
Content-Type: application/json

{
    "title": "By groceries",
    "description": "Potato, carrots, onions"
}

###

PUT  {{TodoApi_HostAddress}}/todos/{{id}}
Content-Type: application/json

{
    "title": "Clean the house",
    "description": "Kitchen, living room",
    "isCompleted": true
}

###

DELETE {{TodoApi_HostAddress}}/todos/{{id}}

###
