@TodoApi_HostAddress = http://localhost:5024
@id = d9c91c3d-4580-434f-8137-21c2cd2c6a1e


GET {{TodoApi_HostAddress}}/todos/
Accept: application/json

###

POST {{TodoApi_HostAddress}}/todos
Content-Type: application/json

{
    "title": "Clean the house",
    "description": "Kitchen, living room, and bathroom"
}

###

PUT  {{TodoApi_HostAddress}}/todos/{{id}}
Content-Type: application/json

{
    "title": "Clean the house",
    "description": "Kitchen, living room, and bathroom"
    "isCompleted": true
}

###

DELETE {{TodoApi_HostAddress}}/todos/{{id}}

###
